#!/usr/bin/env python3
"""Generate a Klipper include file with host IP and hostname.

This avoids any Moonraker dependency by writing values directly into
`local/generated/network_info_values.cfg` before Klipper starts.
"""

import ipaddress
import os
from pathlib import Path
import socket
import subprocess
import sys
import tempfile
import time


def _get_output_path():
    home = Path(os.environ.get("HOME") or str(Path.home()))
    return home / "printer_data" / "config" / "local" / "generated" / "network_info_values.cfg"


def _get_ip():
    """Return a non-loopback IPv4 address if available."""

    def _is_usable_ipv4(value):
        try:
            addr = ipaddress.ip_address(value)
        except ValueError:
            return False
        return addr.version == 4 and not addr.is_loopback

    # Best signal: ask kernel which source IP it would use for outbound traffic.
    for dst in (("8.8.8.8", 80), ("1.1.1.1", 80), ("192.168.0.1", 80)):
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
                s.connect(dst)  # UDP connect does not send packets.
                ip = s.getsockname()[0]
                if _is_usable_ipv4(ip):
                    return ip
        except OSError:
            continue

    # Fallback: addresses resolved for local hostname.
    try:
        for item in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            ip = item[4][0]
            if _is_usable_ipv4(ip):
                return ip
    except OSError:
        pass

    # Last fallback: parse "hostname -I" if present.
    try:
        output = subprocess.check_output(["hostname", "-I"], text=True, timeout=3)
        for token in output.split():
            if _is_usable_ipv4(token):
                return token
    except (FileNotFoundError, subprocess.SubprocessError, OSError):
        pass

    return "no network"


def _escape_klipper_string(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _write_values_cfg(ip, hostname):
    output_path = _get_output_path()
    content = (
        "# Auto-generated by get_network_info.py.\n"
        "# Do not edit manually; this file is refreshed on boot.\n"
        "[gcode_macro _NETWORK_INFO]\n"
        f'variable_ip: "{_escape_klipper_string(ip)}"\n'
        f'variable_hostname: "{_escape_klipper_string(hostname)}"\n'
        "gcode:\n"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="\n",
        dir=output_path.parent,
        delete=False,
    ) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)

    tmp_path.replace(output_path)


def _get_ip_with_retries(attempts=8, delay=1.0):
    for _ in range(attempts):
        ip = _get_ip()
        if ip != "no network":
            return ip
        time.sleep(delay)
    return "no network"


def main():
    ip = _get_ip_with_retries()
    hostname = socket.gethostname()

    try:
        _write_values_cfg(ip, hostname)
    except Exception as exc:
        print(f"network-info: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
